### ISSUE TITLE
[Feature request] Allow to specify priority and assignee

### ISSUE THREAD

**Issue by FilipB** [CSPI-QE/firewatch#12]
It would be helpful to be able to specify priority of generated jira and also to assign it to given user.

**Comment by calebevans** [comment]
@FilipB could the default assignee be handled using a Jira component? I know you can set the assignee in the component, and we have just recently added that functionality in [PR#11](https://github.com/CSPI-QE/firewatch/pull/11).

I am open to adding this functionality, just want to make sure there isn't already a way to do this as I don't want to crowd the config values too much.

**Comment by FilipB** [comment]
Hi @calebevans consider this as nice to have feature. It will help with the triage but it's low priority.
Having default assignee for a component is not compatible with our workflow. We can skip the assignee but having possibility to set priority would be definitely helpful as we consider interop issues critical or even blokers so it would get better visibility.
