### ISSUE TITLE
[Feature Request] Close or update validation tracker task

### ISSUE THREAD

**Issue by nstielau** [CSPI-QE/firewatch#14]
This is potentially a one-off use-case, but I thought I'd share.

In the OpenShift 4.Next working group, we have a Jira tracker for collecting feedback on an Engineering Candidate (EC) build.  It seems like there is a possibility of triggering tests based on an event, like the publishing of a new Engineering Candidate build.

We currently keep a tracker for the different feedback we'd like to collect, e.g. https://issues.redhat.com/browse/FDN-403

The idea here is that firewatch tasks could look up the active tracker somehow, and close out the relevant subtask if that tests passes, and leave a comment if the tests fail.  That way, it's easy to look at the feedback tracker, of which some are automated and some are manual, and see a overall picture of the feedback from the EC.

For example, there might be a Managed Service feedback and an InterOp feedback and a Perf&Scale subtask.  Maybe the first two are automated via tests and Firewatch, and the Perf&Scale still requires a manual update.

```
As a person contributing to and managing OpenShift Engineering Candidate builds
I want to automatically close feedback substasks when associated tests pass
So that I can understand the feedback for the EC with less overhead
```

**Comment by calebevans** [comment]
Hi @nstielau this is certainly a possibility! I would love to set up a meeting with you to maybe get some more context before starting a feature like this. I will reach out to you via Slack to get something set up :)

**Comment by calebevans** [comment]
@nstielau I know we discussed this awhile ago and you said you needed to gather some more information to see if this was something you wanted us to work on. Would you like us start some work on this?

**Comment by nstielau** [comment]
@calebevans thanks for reaching out.  I'm not interesting in pursing this at present.  I'll close this out.
