### ISSUE TITLE
[Feature Request] Allow Security Level to be set on firewatch created tickets

### ISSUE THREAD

**Issue by ascerra** [CSPI-QE/firewatch#24]
Description: When a ticket is created in a Jira project that has different Security levels we should be able to configure firewatch to set the security level on ticket creation.

Reason: This feature would be in preparation for filing security issues against OpenShift CI runs. If we ever start scraping the OpenShift CI logs for security vulnerabilities then we can use firewatch to create a ticket to document the problem. Though we can't document security risks publicly so this feature would need to exist first.

Priority: LOW (if we ever create a security tool for OpenShift CI logs this will become more important.)

**Comment by calebevans** [comment]
Thanks for the request - I may sneak this into a PR soon, depending on how complex it is :)
