### ISSUE TITLE
[Bug] Firewatch Returns a FileExistsError When Downloading Files if a Duplicate is Found in Artifacts Folder

### ISSUE THREAD

**Issue by calebevans** [CSPI-QE/firewatch#27]
**Logs**
- [Firewatch logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.14-lp-interop-acm-interop-aws/1688429940787122176/artifacts/acm-interop-aws/firewatch-report-issues/build-log.txt)
- [Failed job logs](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.14-lp-interop-acm-interop-aws/1688429940787122176)
- [Slack message for when this was reported](https://redhat-internal.slack.com/archives/C04PK4QPSR1/p1691432002331359)

These errors are a result of the `junit_cypress-e12da092e6d1445d34eeb8ecafebfb86.xml` and `junit_cypress-f28271158292282bdda64a2525e57175.xml` files existing in both the [`artifacts/reports/`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.14-lp-interop-acm-interop-aws/1688429940787122176/artifacts/acm-interop-aws/acm-tests-clc-create/artifacts/reports/) folder for that step and the [`artifacts/reports/ocp_interop/`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.14-lp-interop-acm-interop-aws/1688429940787122176/artifacts/acm-interop-aws/acm-tests-clc-create/artifacts/reports/ocp_interop/) directories:

**`artifacts/reports/`**
![image](https://github.com/CSPI-QE/firewatch/assets/44474682/5ea7b2f8-bd38-4a63-81d9-72997b3bda9b)

**`artifacts/reports/ocp_interop/`**
![image](https://github.com/CSPI-QE/firewatch/assets/44474682/6127a141-c8e9-4b5b-bff5-ae2b2dc923e1)

**Comment by ascerra** [comment]
To me, we just have to be sure that we catch any issues so I think option is the better option.

If we do get complaints or dislike the comment duplication then this is something that can be solved from the scenario's perspective. 

I don't consider it good practice to have duplicate XMLs in these artifacts so I like the idea of making sure firewatch is catching issues as its highest priority then any other concerns can be dealt with at the scenario level.
